### ISSUE TITLE
GlassTinter Error Message

### ISSUE THREAD

**Issue by Squidknig** [shiggityshaggs/PlanetCrafterPlugins#1]
I am receiving an error in Glass Tinter

[Warning:   BepInEx] Skipping [SSPCP_GlassTinter 1.1.0] because a newer version exists (SSPCP_GlassTinter 1.1.0)

**Comment by akarnokd** [comment]
Caused by having two plugin annotations on separate classes:

https://github.com/shiggityshaggs/PlanetCrafterPlugins/blob/main/GlassTinter/Plugin.cs#L5
https://github.com/shiggityshaggs/PlanetCrafterPlugins/blob/main/GlassTinter/GlassHandler.cs#L11

**Comment by shiggityshaggs** [comment]
Thanks for the feedback, both of you!
Fixed in [1.4.3](https://github.com/shiggityshaggs/PlanetCrafterPlugins/releases/tag/GlassTinter)
